# Generated by Django 5.0.1 on 2024-03-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='foobar', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='foobar', max_length=20),
        ),
    ]
